### ISSUE TITLE
Image with the motor axle on the platters

### ISSUE THREAD

**Issue by bustavo** [channemann/push-button-get-candy#4]
Hi Chris,

Could you please add an image with the motor axle on the platter hole? I'd like to see how that part is like...

**Comment by channemann** [comment]
Let me know if those are what you're looking for

**Comment by bustavo** [comment]
Yes! Thanks! Closing!

**Comment by channemann** [comment]
As a follow-on, here are some links to 3D files of the servo:
https://grabcad.com/library/micro-servo-9g-1
https://grabcad.com/library/micro-servo-9g-3

**Comment by bustavo** [comment]
Thanks @channemann! I found one on Thingiverse what wasn't exactly the same as a "standard servo" these will be much better!
